import animateLogo from "./modules/animateLogo";
import buttonAnimation from "./modules/buttonAnimation";
import init3DModel from "./modules/init3DModel";
import hoverPortrait from "./modules/hoverPortrait";
import animateOnScrollMainSection from "./modules/animateOnScrollMainSection";
import updateRouteLine from "./modules/updateRouteLine";
import animateOnScrollSectionAbout from "./modules/animateOnScrollSectionAbout";
import animateDate from "./modules/animateDate";
import animateOnScrollPortfolioSection from "./modules/animateOnScrollPortfolioSection";
import hoverCardPortfolio from "./modules/hoverCardPortfolio";
import animateProgress from "./modules/animateProgress";
import game from "./modules/game";
import initSlider from "./modules/initSlider";

animateOnScrollMainSection();
animateOnScrollSectionAbout();
animateOnScrollPortfolioSection();
hoverCardPortfolio();
animateProgress();
game();
animateDate();
updateRouteLine();
hoverPortrait();
animateLogo();
buttonAnimation();
initSlider();
init3DModel();